# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Disable mounting of vagrant folder as its not supported on xenserver
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.box_check_update = false

  # Disable checking for vbguest versions as its not supported on xenserver
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.network :private_network, :auto_config => false , :ip => "10.10.10.10"
  
  config.vm.provider "virtualbox" do |vb|
    
    vb.gui = false
    
    host = RbConfig::CONFIG['host_os']
    host_cpus = 0
    host_memory = 0
    
    if host =~ /darwin/
      host_cpus = `sysctl -n hw.ncpu`.to_i
      host_memory = `sysctl -n hw.memsize`.to_i
    elsif host =~ /linux/
      host_cpus = `nproc`.to_i
      host_memory = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i * 1024
    end

    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--cpus"  , host_cpus.to_s ]
    vb.customize ["modifyvm", :id, "--memory"  , (host_memory / 1024 / 1024 / 2).to_s ]

    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all" ]
  end

  config.vm.provision "shell", path: "bootstrap.sh"

end
